Repository netlify/remix-compute, pull requests merged in 2024-05, with the labels that each got.

#313 chore: port e2e tests from Cypress to Playwright, plus spring cleaning
  .eslintrc.js
  .github/workflows/e2e-demo.yml
  .github/workflows/e2e-edge-demo.yml
  .github/workflows/test.yml
  .gitignore
  cypress.config.ts
  cypress/.eslintrc.js
  cypress/config/edge-cypress.config.ts
  cypress/e2e/smoke.spec.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  demos/demo-site/netlify.toml
  demos/edge-demo-site/package.json
  package.json
  packages/remix-adapter/package.json
  packages/remix-runtime/package.json
  playwright.config.ts
  pnpm-lock.yaml
  tests/e2e/smoke.spec.ts
  tsconfig.json
  vitest.config.ts
Labels: type: chore

#317 fix(edge): externalize node builtins
  .husky/commit-msg
  .npmrc
  package.json
  packages/remix-edge-adapter/src/plugin.ts
  pnpm-lock.yaml
Labels: type: bug, automerge

#212 fix: update `engines` field
  package.json
  packages/remix-adapter/package.json
  packages/remix-edge-adapter/package.json
  packages/remix-runtime/package.json
Labels: automerge

#329 chore: inject correct transitive deps in e2e tests
  tests/e2e/support/deploy-to-netlify.ts
Labels: type: chore

#333 chore: fix duplicate `engines` in `package.json`
  packages/remix-edge-adapter/package.json
Labels: type: chore

#355 chore(renovate): configure @remix-run bumps in test fixtures
  renovate.json
  renovate.json5
Labels: type: chore

#361 ci: add workflow to notify on Remix bump failures
  .github/workflows/failure-notifier.yml
Labels: type: chore

#365 ci: fix Remix bump failure notifier workflow
  .github/workflows/failure-notifier.yml
Labels: type: chore

#364 test: add test asserting loader headers can be set on response
  tests/e2e/fixtures/edge-site/app/routes/cached-for-a-year.tsx
  tests/e2e/fixtures/edge-site/app/routes/headers.tsx
  tests/e2e/fixtures/edge-site/app/routes/middleware-header.tsx
  tests/e2e/fixtures/edge-site/app/routes/stale-while-revalidate.tsx
  tests/e2e/fixtures/edge-site/netlify/edge-functions/middleware-header.ts
  tests/e2e/fixtures/edge-site/netlify/functions/purge-cdn.ts
  tests/e2e/fixtures/serverless-site/app/routes/cached-for-a-year.tsx
  tests/e2e/fixtures/serverless-site/app/routes/headers.tsx
  tests/e2e/fixtures/serverless-site/app/routes/middleware-header.tsx
  tests/e2e/fixtures/serverless-site/app/routes/stale-while-revalidate.tsx
  tests/e2e/fixtures/serverless-site/netlify/edge-functions/middleware-header.ts
  tests/e2e/fixtures/serverless-site/netlify/functions/purge-cdn.ts
  tests/e2e/user-journeys.spec.ts
Labels: type: chore
